version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: property_pass
    ports:
      - "5433:5432"  # Changed from 5432 to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    ports:
      - "6380:6379"  # Changed from 6379 to 6380
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
